license: YOUR_LICENSE_KEY_HERE

# EnchantCore Main Configuration File
Settings:
  # Enable verbose console logs for debugging.
  Debug: false

  # Currency system used for enchant upgrades:
  # TOKENS - Uses internal token balance stored in PlayerData.
  # VAULT  - Uses an external economy plugin hooked via Vault.
  CurrencyType: TOKENS # Default is TOKENS

# --- Auto Pickup Settings ---
AutoPickup:
  Enabled: true

# --- Auto Sell Settings ---
AutoSell:
  Enabled: true

  # Time interval (in seconds) between summary messages.
  # Set to 0 or a negative value to disable the summary.
  Summary-Interval: 60
