name: EnchantCore
version: '1.0.0-SNAPSHOT'
main: com.strikesenchantcore.EnchantCore
api-version: '1.13'
authors: [StrikesDev, ItsCoziest]
description: Core plugin for custom enchantments and pickaxe leveling.
softdepend: [Vault, PlaceholderAPI, WorldGuard, ItemsAdder]

commands:
  enchantcore:
    description: Main command for EnchantCore features.
    usage: /enchantcore <subcommand> [args...]
    aliases: [ec, ecore]
    permission: enchantcore.admin
  sellall:
    description: Sells all valid items in your inventory.
    usage: /sellall
    permission: enchantcore.sellall
  ectoggle:
    description: Toggles enchantment activation messages.
    usage: /ectoggle
    aliases: [ectm, togglemessages]
    permission: enchantcore.togglemessages.use
  togglesounds:
    description: Toggles enchantment activation sounds.
    usage: /togglesounds
    aliases: [ects, togglesound]
    permission: enchantcore.togglesounds.use
  toggleanimations: # ADDED
    description: Toggles enchantment animations.
    usage: /toggleanimations
    aliases: [ecta, toggleanim]
    permission: enchantcore.toggleanimations.use
  tokens:
    description: Manage and check Token balances.
    usage: /tokens <subcommand> [args...]
    aliases: [token, tk]
    permission: enchantcore.tokens.balance
  gems:
    description: "Manage and check Gem balances."
    usage: "/gems <help|balance|give|take|set>"
    aliases: [g, gem]
  points:
    description: "Manage Rebirth Points."
    usage: "/<command> [help|balance|give|take|set]"
    aliases: [ rbpoints, rebirthpoints, rebirth-points ]
  crystals:
    description: "Manage and view crystals."
    usage: "/crystals [help|info|give|merge]"
    aliases: [ crystal ]

permissions:
  enchantcore.admin:
    description: Allows usage of all admin commands for EnchantCore (/ec ...).
    default: op
  enchantcore.gui.open:
    description: Allows opening the EnchantCore GUI.
    default: true
  enchantcore.sellall:
    description: Allows usage of the /sellall command.
    default: true
  enchantcore.autosell:
    description: Allows AutoSell functionality if enabled.
    default: true
  enchantcore.autopickup:
    description: Allows AutoPickup functionality if enabled.
    default: true
  enchantcore.togglemessages.use:
    description: Allows usage of the /ectoggle command.
    default: true
  enchantcore.togglesounds.use:
    description: Allows usage of the /togglesounds command.
    default: true
  enchantcore.toggleanimations.use: # ADDED
    description: Allows usage of the /toggleanimations command.
    default: true
  enchantcore.tokens.balance:
    description: Allows checking own token balance (/tokens).
    default: true
  enchantcore.tokens.balance.others:
    description: Allows checking other players' token balance (/tokens balance <player>).
    default: op
  enchantcore.tokens.modify.*:
    description: Allows modifying token balances (give/take/set).
    default: op
    children:
      enchantcore.tokens.modify.give: true
      enchantcore.tokens.modify.take: true
      enchantcore.tokens.modify.set: true
  enchantcore.tokens.modify.give:
    description: Allows giving tokens (/tokens give ...).
    default: op
  enchantcore.tokens.modify.take:
    description: Allows taking tokens (/tokens take ...).
    default: op
  enchantcore.tokens.modify.set:
    description: Allows setting token balance (/tokens set ...).
    default: op
  enchantcore.gems.balance:
    description: Allows checking own gem balance (/gems).
    default: true
  enchantcore.gems.balance.others:
    description: Allows checking other players' gem balance (/gems balance <player>).
    default: op
  enchantcore.gems.modify.*:
    description: Allows modifying gem balances (give/take/set).
    default: op
    children:
      enchantcore.gems.modify.give: true
      enchantcore.gems.modify.take: true
      enchantcore.gems.modify.set: true
  enchantcore.gems.modify.give:
    description: Allows giving gems (/gems give ...).
    default: op
  enchantcore.gems.modify.take:
    description: Allows taking gems (/gems take ...).
    default: op
  enchantcore.gems.modify.set:
    description: Allows setting gem balance (/gems set ...).
    default: op
  enchantcore.points.admin:
    description: "Grants access to all admin-level points commands."
    children:
      enchantcore.points.modify.give: true
      enchantcore.points.modify.take: true
      enchantcore.points.modify.set: true
      enchantcore.points.balance.others: true
  enchantcore.points.player:
    description: "Grants access to basic player points commands."
    children:
      enchantcore.points.balance: true
  enchantcore.points.balance:
    description: "Allows a player to check their own point balance."
    default: true # All players can check their own balance by default
  enchantcore.points.balance.others:
    description: "Allows checking another player's point balance."
    default: op
  enchantcore.points.modify.give:
    description: "Allows giving points to a player."
    default: op
  enchantcore.points.modify.take:
    description: "Allows taking points from a player."
    default: op
  enchantcore.points.modify.set:
    description: "Allows setting a player's point balance."
    default: op
  enchantcore.crystals.admin:
    description: "Grants access to all admin-level crystals commands."
    default: op
    enchantcore.crystals.use:
      description: "Allows a player to use basic crystals commands."
      default: true

